/home/niels/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
loaded from disk: -data-music_speech-music_wav--data-music_speech-speech_wav-_raw
loaded from disk: -data-columbia_music_speech_corpus-test-music-vocals-data-columbia_music_speech_corpus-test-speech_raw
Col test data 
X: (40, 24, 1500, 3), Y: (40,)


-------
Analyze simple_cnn on GTZAN - SpectroData
music sample:  (24, 1500, 3)
get model: input shape [24, 3000, 3]
2018-09-19 07:35:55.253999: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Y_p (2, 991)
y_time (991,)
y_time (991,)
music (24, 3000, 3)
w_speech (1, 3000, 1)
audio (24, 3000, 3)
y (991,)
/home/niels/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py:537: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)
loaded from disk: -data-columbia_music_speech_corpus-train-music-data-columbia_music_speech_corpus-train-speech_raw
loaded from disk: -data-columbia_music_speech_corpus-test-music-vocals-data-columbia_music_speech_corpus-test-speech_raw
Col test data 
X: (40, 24, 1500, 3), Y: (40,)


-------
Analyze simple_cnn on columbia-train - SpectroData
music sample:  (24, 1500, 3)
get model: input shape [24, 1500, 3]
Y_p (2, 491)
y_time (491,)
y_time (491,)
music (24, 1500, 3)
w_speech (1, 1500, 1)
audio (24, 1500, 3)
y (491,)
The program exited via sys.exit(). Exit status: None
> /home/niels/Dokumente/Informatik/Master/music/rhythm-extraction/src/cv_experiment.py(1)<module>()
-> import os
(Pdb) Traceback (most recent call last):
  File "/home/niels/anaconda3/lib/python3.6/pdb.py", line 1667, in main
    pdb._runscript(mainpyfile)
  File "/home/niels/anaconda3/lib/python3.6/pdb.py", line 1548, in _runscript
    self.run(statement)
  File "/home/niels/anaconda3/lib/python3.6/bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/niels/Dokumente/Informatik/Master/music/rhythm-extraction/src/cv_experiment.py", line 1, in <module>
    import os
  File "/home/niels/Dokumente/Informatik/Master/music/rhythm-extraction/src/cv_experiment.py", line 1, in <module>
    import os
  File "/home/niels/anaconda3/lib/python3.6/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/niels/anaconda3/lib/python3.6/bdb.py", line 66, in dispatch_line
    self.user_line(frame)
  File "/home/niels/anaconda3/lib/python3.6/pdb.py", line 261, in user_line
    self.interaction(frame, None)
  File "/home/niels/anaconda3/lib/python3.6/pdb.py", line 352, in interaction
    self._cmdloop()
  File "/home/niels/anaconda3/lib/python3.6/pdb.py", line 321, in _cmdloop
    self.cmdloop()
  File "/home/niels/anaconda3/lib/python3.6/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
ValueError: I/O operation on closed file.
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /home/niels/anaconda3/lib/python3.6/cmd.py(126)cmdloop()
-> line = input(self.prompt)
(Pdb) Traceback (most recent call last):
  File "/home/niels/anaconda3/lib/python3.6/pdb.py", line 1667, in main
    pdb._runscript(mainpyfile)
  File "/home/niels/anaconda3/lib/python3.6/pdb.py", line 1548, in _runscript
    self.run(statement)
  File "/home/niels/anaconda3/lib/python3.6/bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/niels/Dokumente/Informatik/Master/music/rhythm-extraction/src/cv_experiment.py", line 1, in <module>
    import os
  File "/home/niels/Dokumente/Informatik/Master/music/rhythm-extraction/src/cv_experiment.py", line 1, in <module>
    import os
  File "/home/niels/anaconda3/lib/python3.6/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/niels/anaconda3/lib/python3.6/bdb.py", line 66, in dispatch_line
    self.user_line(frame)
  File "/home/niels/anaconda3/lib/python3.6/pdb.py", line 261, in user_line
    self.interaction(frame, None)
  File "/home/niels/anaconda3/lib/python3.6/pdb.py", line 352, in interaction
    self._cmdloop()
  File "/home/niels/anaconda3/lib/python3.6/pdb.py", line 321, in _cmdloop
    self.cmdloop()
  File "/home/niels/anaconda3/lib/python3.6/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
ValueError: I/O operation on closed file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/niels/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/niels/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/niels/anaconda3/lib/python3.6/pdb.py", line 1694, in <module>
    pdb.main()
  File "/home/niels/anaconda3/lib/python3.6/pdb.py", line 1686, in main
    pdb.interaction(None, t)
  File "/home/niels/anaconda3/lib/python3.6/pdb.py", line 352, in interaction
    self._cmdloop()
  File "/home/niels/anaconda3/lib/python3.6/pdb.py", line 321, in _cmdloop
    self.cmdloop()
  File "/home/niels/anaconda3/lib/python3.6/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
ValueError: I/O operation on closed file.
niels@slave:~/Dokumente/Informatik/Master/music/rhythm-extraction/src$ 

